"""empty message

Revision ID: 311c22ae41d1
Revises: 
Create Date: 2018-09-11 16:38:14.905000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311c22ae41d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_tb_auth_addtime'), 'tb_auth', ['addtime'], unique=False)
    op.create_table('tb_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('salesprice', sa.Float(), nullable=True),
    sa.Column('costprice', sa.Float(), nullable=True),
    sa.Column('rewardprice', sa.Float(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_item_addtime'), 'tb_item', ['addtime'], unique=False)
    op.create_table('tb_mscard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('payment', sa.Float(), nullable=True),
    sa.Column('interval', sa.Float(), nullable=True),
    sa.Column('scorerule', sa.Float(), nullable=True),
    sa.Column('scorelimit', sa.Float(), nullable=True),
    sa.Column('valid', sa.SmallInteger(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_mscard_addtime'), 'tb_mscard', ['addtime'], unique=False)
    op.create_table('tb_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('auths', sa.String(length=600), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tb_role_addtime'), 'tb_role', ['addtime'], unique=False)
    op.create_table('tb_vip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('scorerule', sa.Float(), nullable=True),
    sa.Column('scorelimit', sa.Float(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_vip_addtime'), 'tb_vip', ['addtime'], unique=False)
    op.create_index(op.f('ix_tb_vip_endtime'), 'tb_vip', ['endtime'], unique=False)
    op.create_table('tb_msdetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mscard_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('discountprice', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('dates', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['tb_item.id'], ),
    sa.ForeignKeyConstraint(['mscard_id'], ['tb_mscard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pwd', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('id_card', sa.String(length=18), nullable=True),
    sa.Column('jobs', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('frozen', sa.SmallInteger(), nullable=False),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tb_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_card'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_tb_user_addtime'), 'tb_user', ['addtime'], unique=False)
    op.create_table('tb_vipdetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vip_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('discountprice', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['tb_item.id'], ),
    sa.ForeignKeyConstraint(['vip_id'], ['tb_vip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_vipdetail_addtime'), 'tb_vipdetail', ['addtime'], unique=False)
    op.create_index(op.f('ix_tb_vipdetail_endtime'), 'tb_vipdetail', ['endtime'], unique=False)
    op.create_table('tb_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_wechat', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('pnumber', sa.String(length=20), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('id_card', sa.String(length=18), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('freq', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Float(), nullable=True),
    sa.Column('vip_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.ForeignKeyConstraint(['vip_id'], ['tb_vip.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('pnumber')
    )
    op.create_index(op.f('ix_tb_customer_addtime'), 'tb_customer', ['addtime'], unique=False)
    op.create_table('tb_oplog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=600), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_oplog_addtime'), 'tb_oplog', ['addtime'], unique=False)
    op.create_table('tb_userlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_userlog_addtime'), 'tb_userlog', ['addtime'], unique=False)
    op.create_table('tb_billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('paywith', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['tb_customer.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['tb_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_tb_billing_addtime'), 'tb_billing', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_billing_addtime'), table_name='tb_billing')
    op.drop_table('tb_billing')
    op.drop_index(op.f('ix_tb_userlog_addtime'), table_name='tb_userlog')
    op.drop_table('tb_userlog')
    op.drop_index(op.f('ix_tb_oplog_addtime'), table_name='tb_oplog')
    op.drop_table('tb_oplog')
    op.drop_index(op.f('ix_tb_customer_addtime'), table_name='tb_customer')
    op.drop_table('tb_customer')
    op.drop_index(op.f('ix_tb_vipdetail_endtime'), table_name='tb_vipdetail')
    op.drop_index(op.f('ix_tb_vipdetail_addtime'), table_name='tb_vipdetail')
    op.drop_table('tb_vipdetail')
    op.drop_index(op.f('ix_tb_user_addtime'), table_name='tb_user')
    op.drop_table('tb_user')
    op.drop_table('tb_msdetail')
    op.drop_index(op.f('ix_tb_vip_endtime'), table_name='tb_vip')
    op.drop_index(op.f('ix_tb_vip_addtime'), table_name='tb_vip')
    op.drop_table('tb_vip')
    op.drop_index(op.f('ix_tb_role_addtime'), table_name='tb_role')
    op.drop_table('tb_role')
    op.drop_table('tb_order')
    op.drop_index(op.f('ix_tb_mscard_addtime'), table_name='tb_mscard')
    op.drop_table('tb_mscard')
    op.drop_index(op.f('ix_tb_item_addtime'), table_name='tb_item')
    op.drop_table('tb_item')
    op.drop_index(op.f('ix_tb_auth_addtime'), table_name='tb_auth')
    op.drop_table('tb_auth')
    # ### end Alembic commands ###
