"""empty message

Revision ID: 4129b58f26a0
Revises: 
Create Date: 2018-09-10 15:28:29.965000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4129b58f26a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_mscard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('payment', sa.Float(), nullable=True),
    sa.Column('interval', sa.Float(), nullable=True),
    sa.Column('scorerule', sa.Float(), nullable=True),
    sa.Column('scorelimit', sa.Float(), nullable=True),
    sa.Column('valid', sa.SmallInteger(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_mscard_addtime'), 'tb_mscard', ['addtime'], unique=False)
    op.create_foreign_key(None, 'tb_billing', 'tb_customer', ['cust_id'], ['id'])
    op.create_foreign_key(None, 'tb_billing', 'tb_order', ['order_id'], ['id'])
    op.create_foreign_key(None, 'tb_customer', 'tb_vip', ['vip_id'], ['id'])
    op.create_foreign_key(None, 'tb_customer', 'tb_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tb_msdetail', 'tb_mscard', ['mscard_id'], ['id'])
    op.create_foreign_key(None, 'tb_msdetail', 'tb_item', ['item_id'], ['id'])
    op.create_foreign_key(None, 'tb_oplog', 'tb_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tb_user', 'tb_role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'tb_userlog', 'tb_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tb_vipdetail', 'tb_item', ['item_id'], ['id'])
    op.create_foreign_key(None, 'tb_vipdetail', 'tb_vip', ['vip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_vipdetail', type_='foreignkey')
    op.drop_constraint(None, 'tb_vipdetail', type_='foreignkey')
    op.drop_constraint(None, 'tb_userlog', type_='foreignkey')
    op.drop_constraint(None, 'tb_user', type_='foreignkey')
    op.drop_constraint(None, 'tb_oplog', type_='foreignkey')
    op.drop_constraint(None, 'tb_msdetail', type_='foreignkey')
    op.drop_constraint(None, 'tb_msdetail', type_='foreignkey')
    op.drop_constraint(None, 'tb_customer', type_='foreignkey')
    op.drop_constraint(None, 'tb_customer', type_='foreignkey')
    op.drop_constraint(None, 'tb_billing', type_='foreignkey')
    op.drop_constraint(None, 'tb_billing', type_='foreignkey')
    op.drop_index(op.f('ix_tb_mscard_addtime'), table_name='tb_mscard')
    op.drop_table('tb_mscard')
    # ### end Alembic commands ###
